const MONSTERS = [
  {
    id: 87,
    name: "Observateur",
    zone: "Forêt de saphir (Nandor)",
    rang: 3,
    hp: 160,
    esq: 50,
    dm: 40,
    arm: 0,
    res: 8,
    competences: [
      { nom: "Disparition soudaine",            type: "tech_combat" },
      { nom: "Recherche intuitive",             type: "tech_combat" },
      { nom: "Piqûre",                          type: "magie" },
      { nom: "Invisibilité",                    type: "magie" },
      { nom: "Maléfice de nécrose",             type: "magie" },
      { nom: "Rapide",                          type: "don" },
      { nom: "Vulnérabilité lumière_icone 20%", type: "don" },
      { nom: "Résistance ombre_icone 40%",      type: "don" }
    ],
    items: [
      { id: 361, nom: "Masque des ténèbres", emplacement: "Tête" },
      { id: 232, nom: "Dérobade en soie",    emplacement: "Buste" },
      { id: 76,  nom: "Sceptre émeraude",    emplacement: "Une main" },
      { id: 186, nom: "Perle",               emplacement: "Fétiche" }
    ],
    drops: [
      { id: 342, nom: "Encre" },
      { id: 142, nom: "Fibre violette" },
      { id: 0,   nom: "20-40" },
    ],
    description: "Il est difficile de savoir si la peur d'être observé est apparue avant ou après les Observateurs de l'Ombre. Une chose est certaine cependant : leur regard perçant glace le sang, d'autant qu'ils sont la majeure partie du temps fondue dans les ombres au point d'être complètement invisibles, ne laissant que cette horrible sensation d'être surveillé. Apparition sur les murs, ombres s'allongeant sur le sol, leur corps quasi translucide ne se dessine qu'aux rayons de lune qui découpent leur silhouette effroyablement humanoïde. Une vieille légende de Nandor raconte que quiconque voit un Observateur connaît un destin tragique dans les quelques jours à venir."
  },
  {
    id: 85,
    name: "Matagot",
    zone: "Forêt de saphir (Nandor)",
    rang: 3,
    hp: 200,
    esq: 85,
    dm: 40,
    arm: 0,
    res: 0,
    competences: [
      { nom: "Attaque sournoise",          type: "tech_combat" },
      { nom: "Attaque rapide",             type: "tech_combat" },
      { nom: "Disparition soudaine",       type: "tech_combat" },
      { nom: "Permutation",                type: "magie" },
      { nom: "Inflige 1 saignement_icone", type: "don" },
      { nom: "Inflige 1 faille_icone",     type: "don" },
      { nom: "Résistance ombre_icone 20%", type: "don" },
    ],
    items: [
      { id: 162, nom: "Cagoule de l'ombre", emplacement: "Tête" },
      { id: 307, nom: "Tunique de l'ombre", emplacement: "Buste" },
      { id: 362, nom: "Dague sinistre",     emplacement: "Une main" }
    ],
    drops: [
      { id: 342, nom: "Encre" },
      { id: 298, nom: "Clé en ossements" },
      { id: 67,  nom: "Dents" },
      { id: 0,   nom: "20-40" },
    ],
    description: "Les Matagots sont des esprits qui hantent les cimetières. Des âmes-sorcières qui ont pris dans la mort l'apparence de chat noir aux yeux de rubis. Des monstruosités qui peuvent grandir ou rétrécir à volonté dans la pénombre. Leur discrétion est à la hauteur de leur souplesse. Si leur morsure est à craindre, c'est surtout leur sournoiserie qui fait frémir les baroudeurs, même les plus expérimentés. Nombreux sont les voyageurs ayant cru s'en prendre à un matagot et en ressortir vivant, pour finalement se retrouver quelques mètres plus loin, aux mains d'ennemis bien plus nombreux que prévu. Car le matagot a une petite astuce, que ce soit pour attaquer ou pour fuir : si sa proie ne veut pas s'approcher, le chat-sorcier peut bien décider pour lui."
  },
  {
    id: 84,
    name: "Cauchemar",
    zone: "Forêt de saphir (Nandor)",
    rang: 3,
    hp: 200,
    esq: 40,
    dm: 50,
    arm: 9,
    res: 4,
    competences: [
      { nom: "Attaque hypnotique",         type: "tech_combat" },
      { nom: "Tourmenter",                 type: "tech_combat" },
      { nom: "Siphonner",                  type: "tech_combat" },
      { nom: "Inflige 2 terreur_icone",    type: "don" },
      { nom: "Résistance ombre_icone 20%", type: "don" },
    ],
    items: [
      { id: 194, nom: "Casque terrifiant",   emplacement: "Tête" },
      { id: 197, nom: "Plastron terrifiant", emplacement: "Buste" },
      { id: 364, nom: "Crépusculaire",       emplacement: "Une main" }
    ],
    drops: [
      { id: 342, nom: "Encre" },
      { id: 0,   nom: "20-40" },
    ],
    description: "Les Cauchemars sont des spectres alimentés par une haine froide et calculée. La brutalité dont ils font preuve ne rompt jamais le silence qui les entoure. Sous leur habit épais, vous devinez un corps fait d'ombres tangibles dont il est possible de tirer des gerbes de sang couleur encre. La légende veut que ce soient les âmes qui ont péri de par leur mensonge ou leur trahison, condamnés à ne jamais pouvoir s'excuser. Rendus fous par ce silence coupable, ils se délectent des hurlements qu'ils causent, d'autant que leur aura impose un sentiment de frayeur féroce à quiconque les approche. En effet, bien qu'entouré, sitôt que le Cauchemar pose son attention sur vous, vous avez l'intime conviction que personne ne saurait vraiment vous en protéger."
  },
  {
    id: 86,
    name: "Fée maline",
    zone: "Forêt de saphir (Nandor)",
    rang: 3,
    hp: 160,
    esq: 60,
    dm: 40,
    arm: 0,
    res: 4,
    competences: [
      { nom: "Attaque hypnotique",         type: "tech_combat" },
      { nom: "Attaque rapide",             type: "tech_combat" },
      { nom: "Disparition soudaine",       type: "tech_combat" },
      { nom: "Vol de magie",               type: "magie" },
      { nom: "Inflige 2 nécrose_icone",    type: "don" },
      { nom: "Résistance ombre_icone 40%", type: "don" },
    ],
    items: [
      { id: 360, nom: "Robe des ténèbres",  emplacement: "Buste" },
      { id: 363, nom: "Arc funeste",        emplacement: "Deux mains" },
      { id: 149, nom: "Bottines sylvaines", emplacement: "Pieds" }
    ],
    drops: [
      { id: 224, nom: "Ouvrage sylvestre", emplacement: "Une main" },
      { id: 295, nom: "Aile de fée" },
      { id: 342, nom: "Encre" },
      { id: 0, nom: "20-40" },
    ],
    description: "Les fées corrompues par l'Ombre prennent cette couleur significative, celle des cendres qui sont éclairées par la lune. Il est pourtant difficile de la dissocier des autres espèces de fées qui vivent dans les forêts ou dans les marais, puisqu'elles ont tout comme celles-ci un petit corps doté de quatre belles ailes. C'est seulement à la lumière de la lune que leur véritable apparence se dévoile et que les membres de la petite créature se font plus maigrelets, et leurs petits doigts ressemblent à des osselets funestes. Leur rire se veut alors plus carnassier qu'enjoué. Il ne fait dès lors aucun doute que ce qu'elle désire, c'est un peu plus d'engrais pour faire éclore les fleurs nocturnes qui ornent le jardin que vous profanez."
  },
  // {
  //   id: 88,
  //   name: "Princesse Sombre",
  //   zone: "Forêt de saphir (Nandor)",
  //   rang: 4,
  //   hp: 1000,
  //   esq: 80,
  //   dm: 90,
  //   arm: 10,
  //   res: 17,
  //   competences: [
  //     { nom: "Offrir son sang",             type: "tech_combat" },
  //     { nom: "Méditation défensive",        type: "tech_combat" },
  //     { nom: "Drain de vie",                type: "magie" },
  //     { nom: "Légende",                     type: "don" },
  //     { nom: "Endurance",                   type: "don" },
  //     { nom: "Vulnérabilité feu_icone 20%", type: "don" },
  //     { nom: "Résistance ombre_icone 70%",  type: "don" },
  //   ],
  //   items: [
  //     { id: 361, nom: "Masque des ténèbres", emplacement: "Tête" },
  //     { id: 360, nom: "Robe des ténèbres",   emplacement: "Buste" },
  //     { id: 309, nom: "Orbe angélique",      emplacement: "Une main" },
  //     { id: 337, nom: "Eventail noble",      emplacement: "Une main" }
  //   ],
  //   drops: [
  //     { id: 176, nom: "Gemme améthyste" },
  //     { id: 369, nom: "Ame légendaire", emplacement: "Fétiche" },
  //     { id: 177, nom: "Diadème",        emplacement: "Tête" },
  //     { id: 15,  nom: "Potion d'expérience" },
  //     { id: 342, nom: "Encre" },
  //     { id: 0,   nom: "30-50" },
  //   ],
  //   description: "Bellinda de Nandor, sinistrement connue sous le nom de la Princesse Sombre, est la fille de Cerilla de Nandor, dernière descendante du Roi-Musicien Belen. S'il n'en reste désormais qu'un fantôme pâle qui semble plus réel à la lumière des flammes que de la lune, elle fut de son temps condamnée par la population suite aux nombreuses rumeurs de sacrifice humain que la famille Nandor aurait effectué afin de s'assurer le pouvoir. Pourtant, le titre royal ne semble en rien usurpé : la créature éthérée porte sur elle toute la grâce héritée de son sang et un quelque chose, à la fois, de terrifiant. Comme si sa seule présence pouvait drainer en quelque sorte l'énergie ou la hargne qui habite d'ordinaire le cœur des hommes. La légende veut que ceux qui rencontrent la mort de la main de la Princesse Sombre ne peuvent plus jamais mourir et que leur âme est alors piégée dans la Chapelle Nocturne. Une note de plus sur la grande partition. Une note fatidique pour celle dont les doigts atrophiés et douloureux, comme brisés par des coups violents, ne saurait plus jamais jouer la Musique de l'Ombre."
  // },
  // {
  //   id: 96,
  //   name: "Adorateur du Sang",
  //   zone: "Zone ensanglantée (Nandor)",
  //   rang: 3,
  //   hp: 240,
  //   esq: 50,
  //   dm: 40,
  //   arm: 8,
  //   res: 2,
  //   competences: [
  //     { nom: "Attaque puissante", type: "tech_combat" },
  //     { nom: "Entailler",         type: "tech_combat" },
  //     { nom: "Sauvagerie",        type: "don" },
  //     { nom: "Endurance",         type: "don" },
  //   ],
  //   items: [
  //     { id: 11,  nom: "Heaume",            emplacement: "Tête" },
  //     { id: 106, nom: "Ceinture de force", emplacement: "Buste" },
  //     { id: 244, nom: "Hache double",      emplacement: "Deux mains" },
  //     { id: 30,  nom: "Jambières",         emplacement: "Pieds" }
  //   ],
  //   variantes: [
  //     [
  //       { id: 245, nom: "Guillotineuse", emplacement: "Deux mains" },
  //     ],
  //   ],
  //   drops: [
  //     { id: 210, nom: "Sang" },
  //     { id: 178, nom: "Potion de vigueur" },
  //     { id: 0,   nom: "20-40" },
  //   ],
  //   description: "Les Adorateurs sont les bourreaux des cultistes, des êtres qui trouvèrent dans cette nouvelle idéologie une nouvelle façon de vivre ce qui jadis leur était interdit. À quoi bon s’en faire de tuer dans un monde où la mort est partout après tout ? Leur soif de sang ne sera épanchée que le jour où la dernière tête du dernier vivant tombera, et comme il en vient régulièrement, des aventuriers pensant pouvoir les sauver, cela fait bien leur affaire. Si d’aventure, vous voudriez leur faire entendre raison, vous ne tomberez que sur un visage émacié, à l’haleine suintant le fer et balbutiant des mots obscènes, vous faisant comprendre bien vite que la chose qui se tient devant vous n’est plus que l’ombre d’un humain. Un fou aurait plus d’humanité."
  // },
  // {
  //   id: 97,
  //   name: "Pactisant du Sang",
  //   zone: "Zone ensanglantée (Nandor)",
  //   rang: 3,
  //   hp: 200,
  //   esq: 40,
  //   dm: 40,
  //   arm: 0,
  //   res: 9,
  //   competences: [
  //     { nom: "Offrir son sang",        type: "tech_combat" },
  //     { nom: "Méditation défensive",   type: "tech_combat" },
  //     { nom: "Piqûre",                 type: "magie" },
  //     { nom: "Maléfice de saignement", type: "magie" },
  //     { nom: "Sauvagerie",             type: "don" },
  //   ],
  //   items: [
  //     { id: 129, nom: "Tenue améthyste",    emplacement: "Buste" },
  //     { id: 366, nom: "Sceptre de pouvoir", emplacement: "Une main" },
  //     { id: 367, nom: "Codex de pouvoir",   emplacement: "Une main" },
  //     { id: 77,  nom: "Souliers en soie",   emplacement: "Pieds" }
  //   ],
  //   drops: [
  //     { id: 210, nom: "Sang" },
  //     { id: 45,  nom: "Viande" },
  //     { id: 221, nom: "Fiole d'argent" },
  //     { id: 298, nom: "Clé en ossements" },
  //     { id: 0,   nom: "20-40" },
  //   ],
  //   description: "Les pactisants sont poussés leur recherche de solution jusqu’à sacrifier une partie d’eux-mêmes afin d’obtenir d’un autre monde, d’une autre réalité, des pouvoirs bien obscurs. Souvent insuffisants, ils cherchent désormais comment tirer de cet autre monde qu’ils ont pu entrevoir le pouvoir nécessaire non plus pour réparer les maux, mais pour devenir plus puissants encore. Car avoir vu l’autre-monde les a rendu aveugles, comme à chaque fois qu’on observe l’abîme et qu’il nous observe en retour. Ce qu’ils ont vu là-bas a dévoré leur humanité et ils ne restent désormais d’eux qu’une coquille désespérée d’obtenir davantage, libérant des diablotins pour assouvir leur pulsion de domination et de mort."
  // },
  // {
  //   id: 100,
  //   name: "Limon de Sang",
  //   zone: "Zone ensanglantée (Nandor)",
  //   rang: 3,
  //   hp: 200,
  //   esq: 50,
  //   dm: 40,
  //   arm: 6,
  //   res: 6,
  //   competences: [
  //     { nom: "Attaque défensive",              type: "tech_combat" },
  //     { nom: "Inflige 2 saignement_icone",     type: "don" },
  //     { nom: "Inflige 2 lenteur_icone",        type: "don" },
  //     { nom: "Vulnérabilité foudre_icone 20%", type: "don" },
  //   ],
  //   items: [
  //   ],
  //   drops: [
  //     { id: 210, nom: "Sang" },
  //     { id: 68,  nom: "Estomac" },
  //     { id: 73,  nom: "Tripes" },
  //     { id: 15,  nom: "Potion d'expérience" },
  //     { id: 0,   nom: "20-40" },
  //   ],
  //   description: "La gelée de sang émerge du sol ou tombe mollement des arbres qui généralement les abritent. Il apparaît comme une masse visqueuse, d’un carmin brillant. Ses contours fluctuants semblent constamment en mutation alors qu’il tente par tous les moyens de piéger toute source de vie à même son corps. Des éclats d’os et de métal sont piégés dans sa gelée sinistre, témoins des précédentes victimes à peine digérées. Une odeur de soufre et de fer flotte partout où il va, indiquant bien souvent sa présence avant qu’on ne l’aperçoive. La simple vue de ce limon éveille généralement chez les aventuriers une frayeur toute primale."
  // },
  // {
  //   id: 101,
  //   name: "Avatar de Sang",
  //   zone: "Zone ensanglantée (Nandor)",
  //   rang: 4,
  //   hp: 1000,
  //   esq: 60,
  //   dm: 60,
  //   arm: 10,
  //   res: 10,
  //   competences: [
  //     { nom: "Enchaîner",                      type: "tech_combat" },
  //     { nom: "Attaque rapide",                 type: "tech_combat" },
  //     { nom: "Légende",                        type: "don" },
  //     { nom: "Catalyste saignement_icone",     type: "don" },
  //     { nom: "Inflige 3 saignement_icone",     type: "don" },
  //     { nom: "Inflige 2 lenteur_icone",        type: "don" },
  //     { nom: "Vulnérabilité foudre_icone 20%", type: "don" },
  //   ],
  //   items: [
  //   ],
  //   drops: [
  //     { id: 369, nom: "Ame légendaire",       emplacement: "Fétiche" },
  //     { id: 250, nom: "Orbe démon",           emplacement: "Une main" },
  //     { id: 228, nom: "Talisman du centaure", emplacement: "Fétiche" },
  //     { id: 15,  nom: "Potion d'expérience" },
  //     { id: 210, nom: "Sang" },
  //     { id: 259, nom: "Potion de vie" },
  //     { id: 0,   nom: "30-50" },
  //   ],
  //   description: "On devine un corps fluide et visqueux sous le sang, à la silhouette féminine. Il semble sculpté à partir d’une matière fluide mais poisseuse, élégante et dérangeante à la fois. Sa peau reflète de multiples nuances de carmin, créant de subtil dégradé de pourpre, donnant l’impression d’une cascade de sang en perpétuel mouvement. Elle semble tout à la fois solide et liquide, douce et sinistre, à l’instar de la petite mélodie qui s’échappe d’elle. Comme un murmure lointain et indiscernable, il provoque des émotions contradictoires, de fascination et de crainte. A proximité, la seule chose qui frappe est le rythme très régulier des battements de son cœur qui vous parvient, éclipsant tous les autres sons."
  // },
  {
    id: 82,
    name: "Flammeliée",
    zone: "Zone ardente (Nandor)",
    rang: 3,
    hp: 200,
    esq: 40,
    dm: 40,
    arm: 14,
    res: 0,
    competences: [
      { nom: "Enchaîner",                type: "tech_combat" },
      { nom: "Attaque défensive",        type: "tech_combat" },
      { nom: "Exécuter",                 type: "tech_combat" },
      { nom: "Inflige 1 brulure_icone",  type: "don" },
      { nom: "Résistance feu_icone 60%", type: "don" },
    ],
    items: [
      { id: 354, nom: "Armure de la fournaise",   emplacement: "Buste" },
      { id: 357, nom: "Manicle embrasée",         emplacement: "Une main" },
      { id: 355, nom: "Bouclier de la fournaise", emplacement: "Une main" },
    ],
    variantes: [
      [
        { id: 328, nom: "Badelaire ardent" ,        emplacement: "Une main" },
        { id: 355, nom: "Bouclier de la fournaise", emplacement: "Une main" },
      ],
    ],
    drops: [
      { id: 343, nom: "Poudre noire" },
      { id: 0,   nom: "20-40" },
    ],
    description: "Le Flammeliée est un diable de feu dont le corps apparaît seulement à la lueur des flammes. Monstre sanguinaire que seul le sang apaise, il est la main qui châtie au nom de l'Ardent et un véritable boucher pour les villages qu'il incendie en même temps qu'il massacre. Redouté par beaucoup, il est, selon les légendes, l'âme des guerriers qui furent immolés par les flammes de l'Ardent et qui, jugés trop innocents ou pas assez passionnés, furent maudits à vivre par et pour l'Ardent jusqu'à l'éternité. Certaines légendes veulent que chaque Flammeliée possède une braise-coeur et qui, si elle est éteinte, sauve l'âme du malheureux piégé dans son tourment incandescent."
  },
  {
    id: 79,
    name: "Lampade",
    zone: "Zone ardente (Nandor)",
    rang: 3,
    hp: 160,
    esq: 60,
    dm: 70,
    arm: 0,
    res: 0,
    competences: [
      { nom: "Attaque précise",          type: "tech_combat" },
      { nom: "Enchaîner",                type: "tech_combat" },
      { nom: "Incendie",                 type: "magie" },
      { nom: "Inflige 1 brulure_icone",  type: "don" },
      { nom: "Résistance feu_icone 20%", type: "don" },
    ],
    items: [
      { id: 191, nom: "Bliaut",            emplacement: "Buste" },
      { id: 356, nom: "Fouet enflammé",    emplacement: "Une main" },
      { id: 337, nom: "Eventail noble",    emplacement: "Une main" },
      { id: 229, nom: "Chaussons en soie", emplacement: "Pieds" },
    ],
    drops: [
      { id: 343, nom: "Poudre noire" },
      { id: 438, nom: "Elixir d'énergie" },
      { id: 0,   nom: "20-40" },
    ],
    description: "Les Lampades sont des nymphes de l'Ardent, dont les flammes lèchent leur nuque à la façon d'une cascade de cheveux roux. Leur corps est semble-t-il couvert d'une épaisse suie noire ce qui leur donne cet aspect sombre et terreux. Lorsqu'elles se déplacent, elles sont aussi légères et nébuleuses que la flammèche qui vacille au vent. D'une nature dominante, les lampades ont pour arme un fouet de feu qui lacère et cautérise à la fois les plaies, ne permettant pas à sa proie de mourir, comme pour mieux se délecter de sa souffrance. Attirantes derrière leur aspect de diable, nombreux sont ceux qui se sont faits surprendre par la précision de leurs coups et la rapidité d'exécution de celles qui dansent dans les flammes."
  },
  {
    id: 80,
    name: "Fiélon",
    zone: "Zone ardente (Nandor)",
    rang: 3,
    hp: 160,
    esq: 65,
    dm: 65,
    arm: 0,
    res: 3,
    competences: [
      { nom: "Méditation défensive",     type: "tech_combat" },
      { nom: "Boule de feu",             type: "magie" },
      { nom: "Incendie",                 type: "magie" },
      { nom: "Rapide",                   type: "don" },
      { nom: "Résistance feu_icone 20%", type: "don" },
    ],
    items: [
      { id: 21,  nom: "Pélerine en soie",  emplacement: "Buste" },
      { id: 455, nom: "Bâton d'hérétique", emplacement: "Deux mains" },
      { id: 77,  nom: "Souliers en soie",  emplacement: "Pieds" },
      { id: 20,  nom: "Bague rubis",       emplacement: "Fétiche" },
    ],
    drops: [
      { id: 343, nom: "Poudre noire" },
      { id: 131, nom: "Potion d'éther" },
      { id: 0,   nom: "20-40" },
    ],
    description: "Les Fiélons se trouvent plutôt vers le bas de la pyramide des enfers, mais ils n'en sont pas moins dangereux. Mesquins, sournois et surtout rapides, les Fiélons sont, selon quelques légendes, les âmes des traîtres qui ne se firent jamais pardonner. Cela explique en partie leur méthode qui consiste à lancer des boules de feu et fuir en ricanant bruyamment. D'un fond bête et méchant, les fiélons sont attirés par le sang. Ces créatures sont, malgré une magie particulièrement vivace, trop bêtes pour être domestiqués et ont une certaine tendance à être de très mauvais compagnons, tentant de sournoisement vous trahir à la moindre occasion, y compris de face et en plein jour."
  },
  {
    id: 81,
    name: "Sonneur ardent",
    zone: "Zone ardente (Nandor)",
    rang: 3,
    hp: 200,
    esq: 40,
    dm: 50,
    arm: 8,
    res: 0,
    competences: [
      { nom: "Recherche intuitive",           type: "tech_combat" },
      { nom: "Attaque précise",               type: "tech_combat" },
      { nom: "Vigilance",                     type: "tech_combat" },
      { nom: "Incinération",                  type: "magie" },
      { nom: "Inflige 2 saignement_icone",    type: "don" },
      { nom: "Inflige 2 brulure_icone",       type: "don" },
      { nom: "Résistance feu_icone 20%",      type: "don" },
      { nom: "Vulnérabilité glace_icone 20%", type: "don" },
    ],
    items: [
      { id: 200,  nom: "Cloche",  emplacement: "Une main" },
    ],
    drops: [
      { id: 343, nom: "Poudre noire" },
      { id: 359, nom: "Fiole incendiaire" },
      { id: 66, nom: "Crâne" },
      { id: 0,   nom: "20-40" },
    ],
    description: "Le Sonneur ardent est une créature étrange, un spectre qui flotte partout où la guerre approche et qui émet un drôle de son, comme le tintement d'une cloche quand il repère des victimes. Pour certains, il annonce le chaos, pour d'autres, il ne fait que sanctionner de sa présence les champs de bataille que les hommes ont provoqué bien avant lui. Le sourire qui fend son visage s'élargit à chaque fois que la rage gagne du terrain, donnant l'impression aux aventuriers de bien souvent leur rire au nez alors que ces derniers s'acharnent pour sauver leur peau. "
  },
  {
    id: 83,
    name: "Prince Rouge",
    zone: "Zone ardente (Nandor)",
    rang: 4,
    hp: 1000,
    esq: 60,
    dm: 60,
    arm: 28,
    res: 10,
    competences: [
      { nom: "Attaque puissante",             type: "tech_combat" },
      { nom: "Exécuter",                      type: "tech_combat" },
      { nom: "Attaque défensive",             type: "tech_combat" },
      { nom: "Légende",                       type: "don" },
      { nom: "Rapide",                        type: "don" },
      { nom: "Inflige 1 brulure_icone",       type: "don" },
      { nom: "Résistance feu_icone 50%",      type: "don" },
      { nom: "Vulnérabilité ombre_icone 20%", type: "don" },
    ],
    items: [
      { id: 233, nom: "Bassinet en plume",      emplacement: "Tête" },
      { id: 354, nom: "Armure de la fournaise", emplacement: "Buste" },
      { id: 358, nom: "Hache incandescente",    emplacement: "Deux mains" },
      { id: 260, nom: "Jambières en cuivre",    emplacement: "Pieds" }
    ],
    drops: [
      { id: 173, nom: "Gemme topaze" },
      { id: 369, nom: "Ame légendaire", emplacement: "Fétiche" },
      { id: 15,  nom: "Potion d'expérience" },
      { id: 343, nom: "Poudre noire" },
      { id: 0,   nom: "30-50" },
    ],
    description: "Harwin Larn, aussi appelé le Prince Rouge, fut un des Champions de l'Ardent. La famille Larn fut longuement liée à l'Ardent et son église, mais Harwin abjura ses voeux après sa rencontre avec la Princesse Sombre. Tombé amoureux ou sous le maléfice de l'Ombre selon les versions, il fut condamné par son Faiseur à n'être désormais plus qu'un pantin de sa volonté, incendiant et massacrant quiconque tenterait de retirer sa Hache du rocher. La légende veut que cette Hache lui soit réservée afin que le moment venu, il coupe enfin la tête de la Princesse Sombre, à même la roche qu'elle rendit noire-ombre, entraînant la mort d'une partie de la population du Nandor-est. L'homme, qui est décrit par les récits comme un bel homme d'une trentaine d'années, aux cheveux bruns et aux yeux tendres, se montre désormais caché sous une épaisse armure organique qui lui ceinture le corps jusqu'à la constriction la plus féroce. Cette dernière vous semble faite autant pour le protéger que pour le tenir enfermé dans son rôle. Si vous l'apercevez, voyageur, dites vous bien qu'il est déjà trop tard pour vos prières. Il faudra faire preuve de panache si vous voulez échapper à la Hache du Prince Rouge."
  },
  {
    id: 91,
    name: "Soldat hobgobelin",
    zone: "Zone hobgobeline (Nandor)",
    rang: 3,
    hp: 200,
    esq: 40,
    dm: 40,
    arm: 14,
    res: 2,
    competences: [
      { nom: "Disloquer",              type: "tech_combat" },
      { nom: "Ravager",                type: "tech_combat" },
      { nom: "Coup de bouclier",       type: "tech_combat" },
      { nom: "Bravoure",               type: "don" },
      { nom: "Inflige 1 faille_icone", type: "don" },
      { nom: "Inflige 1 assomé_icone", type: "don" },
    ],
    items: [
      { id: 155, nom: "Cabasset à cornes",  emplacement: "Tête" },
      { id: 81,  nom: "Cuirasse",           emplacement: "Buste" },
      { id: 308, nom: "Lance",              emplacement: "Une main" },
      { id: 29,  nom: "Bouclier à pointes", emplacement: "Une main" },
    ],
    variantes: [
      [
        { id: 60, nom: "Fléau d'armes",      emplacement: "Une main" },
        { id: 29, nom: "Bouclier à pointes", emplacement: "Une main" },
      ]
    ],
    drops: [
      { id: 46, nom: "Viande cuite" },
      { id: 67, nom: "Dents" },
      { id: 0, nom: "20-40" },
    ],
    description: "Le soldat hobgobelin est un bon soldat, en ce que vous verrez rarement des êtres aussi disciplinés issus de la nature. Leur capacité à se coordonner les uns aux autres est bluffante et tout à fait ancrée dans leurs gênes. Ainsi, on voit chez les plus jeunes hobgobelins des comportements similaires où ils peuvent s'en prendre à des plus faibles qu'eux, et toujours en groupe bien organisé. Le soldat hobgobelin collectionne les trophées de guerre et prend plaisir à tuer un ennemi, surtout si ce dernier est plus grand ou a l'air plus fort que lui. Le but d'un soldat hobgobelin est de parvenir en effet à gravir les rangs de la tribu, toujours dans le respect des règles et dans l'idée d'être méritant vis à vis de ce rang."
  },
  {
    id: 94,
    name: "Éclaireur hobgobelin",
    zone: "Zone hobgobeline (Nandor)",
    rang: 3,
    hp: 200,
    esq: 60,
    dm: 40,
    arm: 1,
    res: 1,
    competences: [
      { nom: "Attaque précise",        type: "tech_combat" },
      { nom: "Ravager",                type: "tech_combat" },
      { nom: "Recherche intuitive",    type: "tech_combat" },
      { nom: "Bravoure",               type: "don" },
      { nom: "Inflige 1 faille_icone", type: "don" },
      { nom: "Inflige 1 assomé_icone", type: "don" },
    ],
    items: [
      { id: 317, nom: "Capuche de rôdeur", emplacement: "Tête" },
      { id: 318, nom: "Manteau de rôdeur", emplacement: "Buste" },
      { id: 294, nom: "Arc d'élite",       emplacement: "Deux mains" },
      { id: 156, nom: "Bottines",          emplacement: "Pieds" },
    ],
    variantes: [
      [
        { id: 17, nom: "Arc lourd composite", emplacement: "Deux mains" },
      ]
    ],
    drops: [
      { id: 46, nom: "Viande cuite" },
      { id: 67, nom: "Dents" },
      { id: 0,  nom: "20-40" },
    ],
    description: "Les éclaireurs hobgobelins sont des adversaires redoutables. Leur précision n’équivaut que leur discrétion et leur rapidité sur le terrain. Capables d’avaler de grandes distances sans se fatiguer, leur résistance à la douleur et leur nature belliqueuse est bien connue et partagée avec les autres soldats d’argile comme on les surnomme en Nandor. On reconnaît un éclaireur à son habit qui généralement tend à se fondre davantage avec la nature. Moins agressifs et belliqueux que leurs comparses, ils ont l’air également plus malins et retors quand il s’agit de traquer une proie. Leur nez écrasé est plus large, avec des conduits nasaux plus écartés et leurs oreilles sont également plus longues que celles de leurs frères d’armes ; beaucoup se sont demandés s’il y avait un lien entre leur physique différent et leur place dans la société hobgobeline."
  },
  {
    id: 61,
    name: "Fée givrée",
    zone: "Île au Givre (Kigard)",
    rang: 2,
    hp: 80,
    esq: "?",
    dm: 40,
    arm: 1,
    res: 6,
    competences: [
      { nom: "Méditation défensive",          type: "tech_combat" },
      { nom: "Rafale de givre",               type: "magie" },
      { nom: "Congélation",                   type: "magie" },
      { nom: "Rapide",                        type: "don" },
      { nom: "Vulnérabilité ombre_icone 20%", type: "don" },
    ],
    items: [
      { id: 205, nom: "Sceptre glace", emplacement: "Une main" },
      { id: 182, nom: "Anneau ailé",   emplacement: "Fétiche" },
    ],
    drops: [
      { id: 295, nom: "Aile de fée" },
      { id: 69,  nom: "Oeil" },
      { id: 72,  nom: "Tendon" },
      { id: 0,   nom: "0" },
    ],
  },
  {
    id: 63,
    name: "Élémentaire de glace",
    zone: "Île au Givre (Kigard)",
    rang: 0,
    hp: 150,
    esq: 0,
    dm: 0,
    arm: 0,
    res: 0,
    competences: [
      { nom: "Rafale de givre",            type: "magie" },
      { nom: "Résistance glace_icone 20%", type: "don" },
    ],
    items: [
    ],
    drops: [
      { id: 52,  nom: "Invocation du givre", emplacement: "Une main" },
      { id: 287, nom: "Amulette gelée",      emplacement: "Fétiche" },
      { id: 205, nom: "Sceptre glace",       emplacement: "Une main" },
      { id: 15,  nom: "Potion d'expérience" },
      { id: 0,   nom: "0" },
    ],
  },
  {
    id: 149,
    name: "Dame du Givre",
    zone: "Île au Givre (Kigard)",
    rang: 3,
    hp: 500,
    esq: 40,
    dm: 60,
    arm: 4,
    res: 15,
    competences: [
      { nom: "Méditation défensive",       type: "tech_combat" },
      { nom: "Rafale de givre",            type: "magie" },
      { nom: "Congélation",                type: "magie" },
      { nom: "Elite",                      type: "don" },
      { nom: "Prudence",                   type: "don" },
      { nom: "Morsure du froid",           type: "don" },
      { nom: "Inflige 2 gel_icone",        type: "don" },
      { nom: "Résistance glace_icone 20%", type: "don" },
    ],
    items: [
      { id: 129, nom: "Tenue améthyste",      emplacement: "Buste" },
      { id: 205, nom: "Sceptre glace",        emplacement: "Une main" },
      { id: 256, nom: "Tome de cristal",      emplacement: "Une main" },
      { id: 95, nom: "Mocassins",             emplacement: "Pieds" },
      { id: 447, nom: "Bracelet des étoiles", emplacement: "Fétiche" },
    ],
    drops: [
      { id: 52,  nom: "Invocation du givre", emplacement: "Une main" },
      { id: 221, nom: "Fiole d'argent" },
      { id: 15,  nom: "Potion d'expérience" },
      { id: 0,   nom: "15-35" },
    ],
  },
  {
    id: 14,
    name: "Serpent géant",
    zone: "Île aux Venins (Kigard)",
    rang: 0,
    hp: 120,
    esq: 25,
    dm: "?",
    arm: 6,
    res: "?",
    competences: [
      { nom: "Attaque précise",               type: "tech_combat" },
      { nom: "Disparition soudaine",          type: "tech_combat" },
      { nom: "Inflige 2 poison_icone",        type: "don" },
      { nom: "Vulnérabilité glace_icone 20%", type: "don" },
    ],
    items: [
    ],
    drops: [
      { id: 0,   nom: "?" },
    ],
  },
  {
    id: 22,
    name: "Tarentule",
    zone: "Île aux Venins (Kigard)",
    rang: 0,
    hp: 120,
    esq: 25,
    dm: "?",
    arm: 6,
    res: "?",
    competences: [
      { nom: "Recherche intuitive",     type: "tech_combat" },
      { nom: "Inflige 2 poison_icone",  type: "don" },
      { nom: "Inflige 2 lenteur_icone", type: "don" },
    ],
    items: [
    ],
    drops: [
      { id: 0,   nom: "?" },
    ],
  },
  // {
  //   id: 148,
  //   name: "Gorgone",
  //   zone: "Île aux Venins (Kigard)",
  //   rang: 3,
  //   hp: 500,
  //   esq: "?",
  //   dm: "?",
  //   arm: "?",
  //   res: "?",
  //   competences: [
  //     { nom: "Disparition soudaine",          type: "tech_combat" },
  //     { nom: "Maléfice de poison",            type: "magie" },
  //     { nom: "Maléfice de nécrose",           type: "magie" },
  //     { nom: "Maléfice de saignement",        type: "magie" },
  //     { nom: "Elite",                         type: "don" },
  //     { nom: "Inflige 3 poison_icone",        type: "don" },
  //     { nom: "Inflige 3 poison_rapide_icone", type: "don" },
  //     { nom: "Vulnérabilité glace_icone 20%", type: "don" },
  //   ],
  //   items: [
  //     { id: 193, nom: "Plastron dragon",  emplacement: "Buste" },
  //     { id: 76,  nom: "Sceptre émeraude", emplacement: "Une main" },
  //     { id: 270, nom: "Bouclier dragon",  emplacement: "Une main" },
  //   ],
  //   drops: [
  //     { id: 0, nom: "15-35" },
  //   ],
  // },
  {
    id: 141,
    name: "Janissaire Oublié",
    zone: "Désert de l'oubli (Kigard)",
    rang: 2,
    hp: 120,
    esq: 30,
    dm: "?",
    arm: 0,
    res: "?",
    competences: [
      { nom: "Embuscade",            type: "tech_combat" },
      { nom: "Tir lointain",         type: "tech_combat" },
      { nom: "Disparition soudaine", type: "tech_combat" },
    ],
    items: [
      { id: 439, nom: "Capuche de voleur", emplacement: "Tête" },
      { id: 184, nom: "Pèlerine",          emplacement: "Buste" },
      { id: 128, nom: "Arc composite",     emplacement: "Deux mains" },
    ],
    drops: [
      { id: 365, nom: "Fumigène" },
      { id: 298, nom: "Clé en ossements" },
      { id: 0,   nom: "15-30" },
    ],
  },
  {
    id: 142,
    name: "Sentinelle Oubliée",
    zone: "Désert de l'oubli (Kigard)",
    rang: 2,
    hp: 120,
    esq: 30,
    dm: 30,
    arm: 0,
    res: 0,
    competences: [
      { nom: "Vigilance",         type: "tech_combat" },
      { nom: "Attaque précise",   type: "tech_combat" },
      { nom: "Attaque défensive", type: "tech_combat" },
    ],
    items: [
      { id: 440, nom: "Lunettes d'explorateur", emplacement: "Tête" },
      { id: 184, nom: "Pèlerine",               emplacement: "Buste" },
      { id: 327, nom: "Fusil",                  emplacement: "Deux mains" },
    ],
    variantes: [
      [
        { id: 157, nom: "Fouet-lame", emplacement: "Une main" },
      ],
    ],
    drops: [
      { id: 178,   nom: "Potion de vigueur" },
      { id: 0,   nom: "15-30" },
    ],
  },
  {
    id: 143,
    name: "Assassin Oublié",
    zone: "Désert de l'oubli (Kigard)",
    rang: 2,
    hp: 120,
    esq: 35,
    dm: 30,
    arm: 0,
    res: 0,
    competences: [
      { nom: "Ambidextrie",       type: "tech_combat" },
      { nom: "Attaque sournoise", type: "tech_combat" },
      { nom: "Attaque incisive",  type: "tech_combat" },
    ],
    items: [
      { id: 59,  nom: "Bandana",      emplacement: "Tête" },
      { id: 184, nom: "Pèlerine",     emplacement: "Buste" },
      { id: 452, nom: "Dague courbe", emplacement: "Une main" },
      { id: 47,  nom: "Poignard",     emplacement: "Une main" },
    ],
    drops: [
      { id: 0,   nom: "15-30" },
    ],
  },
  {
    id: 144,
    name: "Prince Oublié",
    zone: "Désert de l'oubli (Kigard)",
    rang: 3,
    hp: 500,
    esq: 65,
    dm: 65,
    arm: 0,
    res: 0,
    competences: [
      { nom: "Vigilance",              type: "tech_combat" },
      { nom: "Ambidextrie",            type: "tech_combat" },
      { nom: "Attaque défensive",      type: "tech_combat" },
      { nom: "Attaque sournoise",      type: "tech_combat" },
      { nom: "Elite",                  type: "don" },
      { nom: "Inflige 2 exposé_icone", type: "don" },
    ],
    items: [
      { id: 146, nom: "Bandana en soie",  emplacement: "Tête" },
      { id: 21,  nom: "Pèlerine en soie", emplacement: "Buste" },
      { id: 141, nom: "Kandjar",          emplacement: "Une main" },
      { id: 311, nom: "Main-gauche",      emplacement: "Une main" },
    ],
    drops: [
      { id: 15, nom: "Potion d'expérience" },
      { id: 438, nom: "Elixir d'énergie" },
      { id: 0, nom: "15-35" },
    ],
  },
  {
    id: 75,
    name: "Sorcière Hanteuse",
    zone: "La Nécropole (Kigard)",
    rang: 3,
    hp: 140,
    esq: 20,
    dm: 35,
    arm: 0,
    res: 9,
    competences: [
      { nom: "Surcharge magique",               type: "tech_combat" },
      { nom: "Piqûre",                          type: "magie" },
      { nom: "Vol de magie",                    type: "magie" },
      { nom: "Inflige 1 terreur_icone",         type: "don" },
      { nom: "Vulnérabilité lumière_icone 20%", type: "don" },
    ],
    items: [
      { id: 286, nom: "Barrette en or",   emplacement: "Tête" },
      { id: 232, nom: "Dérobade en soie", emplacement: "Buste" },
      { id: 454, nom: "Bâton de sorcier", emplacement: "Deux mains" },
    ],
    drops: [
      { id: 131, nom: "Potion d'éther" },
      { id: 0,   nom: "20-40" },
    ],
  },
  {
    id: 76,
    name: "Occultiste Hanteur",
    zone: "La Nécropole (Kigard)",
    rang: 3,
    hp: 140,
    esq: 30,
    dm: 20,
    arm: 0,
    res: 12,
    competences: [
      { nom: "Offrir son sang",                 type: "tech_combat" },
      { nom: "Choc mental",                     type: "magie" },
      { nom: "Maléfice de nécrose",             type: "magie" },
      { nom: "Inflige 1 terreur_icone",         type: "don" },
      { nom: "Vulnérabilité lumière_icone 20%", type: "don" },
    ],
    items: [
      { id: 25,  nom: "Coiffe en soie",   emplacement: "Tête" },
      { id: 232, nom: "Dérobade en soie", emplacement: "Buste" },
      { id: 441, nom: "Baguete",          emplacement: "Une main" },
      { id: 442, nom: "Manuel de magie",  emplacement: "Une main" },
    ],
    drops: [
      { id: 221, nom: "Fiole d'argent" },
      { id: 0,   nom: "20-40" },
    ],
  },
  {
    id: 145,
    name: "Chevalier Automate",
    zone: "La Nécropole (Kigard)",
    rang: 2,
    hp: 180,
    esq: 20,
    dm: 30,
    arm: 18,
    res: 0,
    competences: [
      { nom: "Magie de combat",                type: "tech_combat" },
      { nom: "Tourmenter",                     type: "tech_combat" },
      { nom: "Siphonner",                      type: "tech_combat" },
      { nom: "Impulsion électrique",           type: "don" },
      { nom: "Vulnérabilité foudre_icone 20%", type: "don" },
    ],
    items: [
      { id: 11,  nom: "Heaume",            emplacement: "Tête" },
      { id: 82,  nom: "Armure de plates",  emplacement: "Buste" },
      { id: 316, nom: "Epée de cauchemar", emplacement: "Une main" },    ],
    drops: [
      { id: 90, nom: "Minerai de fer" },
      { id: 0,  nom: "15-30" },
    ],
  },
  {
    id: 146,
    name: "Araignée Automate",
    zone: "La Nécropole (Kigard)",
    rang: 2,
    hp: 160,
    esq: 35,
    dm: 30,
    arm: 7,
    res: 0,
    competences: [
      { nom: "Siphonner",                      type: "tech_combat" },
      { nom: "Electrocution",                  type: "magie" },
      { nom: "Impulsion électrique",           type: "don" },
      { nom: "Inflige 2 lenteur_icone",        type: "don" },
      { nom: "Vulnérabilité foudre_icone 20%", type: "don" },
    ],
    items: [
      { id: 80,  nom: "Griffes",        emplacement: "Une main" },    
      { id: 290, nom: "Sceptre foudre", emplacement: "Une main" },    
    ],
    drops: [
      { id: 90, nom: "Minerai de fer" },
      { id: 0,  nom: "15-30" },
    ],
  },
  {
    id: 147,
    name: "Scarabée Automate",
    zone: "La Nécropole (Kigard)",
    rang: 2,
    hp: 160,
    esq: 45,
    dm: 30,
    arm: 7,
    res: 0,
    competences: [
      { nom: "Siphonner",                      type: "tech_combat" },
      { nom: "Recherche intuitive",            type: "tech_combat" },
      { nom: "Electrocution",                  type: "magie" },
      { nom: "Rapide",                         type: "don" },
      { nom: "Impulsion électrique",           type: "don" },
      { nom: "Vulnérabilité foudre_icone 20%", type: "don" },
    ],
    items: [
      { id: 440, nom: "Lunettes d'explorateur", emplacement: "Tête" },    
      { id: 80,  nom: "Griffes",                emplacement: "Une main" },    
    ],
    drops: [
      { id: 90, nom: "Minerai de fer" },
      { id: 0,  nom: "15-30" },
    ],
  },
 {
    id: 150,
    name: "Avatar de la Peur",
    zone: "La Nécropole (Kigard)",
    rang: 3,
    hp: 500,
    esq: 40,
    dm: 40,
    arm: 10,
    res: "?",
    competences: [
      { nom: "Recherche intuitive",             type: "tech_combat" },
      { nom: "Disparition soudaine",            type: "tech_combat" },
      { nom: "Choc mental",                     type: "magie" },
      { nom: "Subversion",                      type: "magie" },
      { nom: "Elite",                           type: "don" },
      { nom: "Transformation",                  type: "don" },
      { nom: "Inflige 2 terreur_icone",         type: "don" },
      { nom: "Catalyste terreur_icone",         type: "don" },
      { nom: "Vulnérabilité lumière_icone 20%", type: "don" },
    ],
    items: [
      { id: 329, nom: "Masque fantôme",   emplacement: "Tête" },
      { id: 331, nom: "Armure fantôme",   emplacement: "Buste" },
      { id: 76, nom: "Sceptre émeraude",  emplacement: "Une main" },
      { id: 257, nom: "Testament rituel", emplacement: "Une main" },
    ],
    drops: [
      { id: 213, nom: "Champignon hallucinogène" },
      { id: 15,  nom: "Potion d'expérience" },
      { id: 0,   nom: "15-35" },
    ],
  },
  {
    id: 103,
    name: "Voyageur des dimensions",
    zone: "Zone aléatoire (Kigard)",
    rang: 3,
    hp: 180,
    esq: 45,
    dm: "?",
    arm: 0,
    res: "?",
    competences: [
      { nom: "Lire l'avenir",       type: "tech_combat" },
      { nom: "Recherche intuitive", type: "tech_combat" },
      { nom: "Attaque incisive",    type: "tech_combat" },
      { nom: "Rapide",              type: "don" },
    ],
    items: [
      { id: 83,  nom: "Chapeau du nomade", emplacement: "Tête" },    
      { id: 334, nom: "Manteau du nomade", emplacement: "Buste" },    
      { id: 147, nom: "Flamberge",         emplacement: "Deux mains" },    
      { id: 335, nom: "Bottes du nomade",  emplacement: "Pieds" },    
    ],
    drops: [
      { id: 370, nom: "Souvenance de Nandor" },
      { id: 69,  nom: "Oeil" },
      { id: 0,   nom: "20-40" },
    ],
    description: "Les voyageurs dimensionnels possèdent une peau qui rappelle de par sa couleur le satin céleste, tandis que son unique œil, vaste et lumineux, trône au milieu de son front, comme une fenêtre ouverte vers des réalités insoupçonnées. Son apparence, familière et étrangère à la fois, suscite généralement inquiétude et curiosité à tous ceux qui le croisent. C’est qu’il porte des étoffes de mondes inconnus, qu’il parle une langue qui ne sonne comme aucune autre. Il se déplace toujours avec fluidité certaine, malgré une carrure épaisse, et on l’imagine sans mal glisser entre les dimensions avec une aisance déconcertante. Le voyageur dimensionnel est à l’image de ce qu’il est ; un observateur silencieux, discret, captivant par tout le mystère qui entoure son existence. Sa présence est une énigme vivante, une invitation à explorer, allumant souvent une soif d’un voyage transcendant l’espace et le temps."
  },
  {
    id: 23,
    name: "Lutin",
    zone: "Zone aléatoire (Kigard)",
    rang: 2,
    hp: 120,
    esq: "?",
    dm: "?",
    arm: "?",
    res: "?",
    competences: [
      { nom: "Bond athlétique",     type: "tech_combat" },
      { nom: "Subterfuge mystique", type: "tech_combat" },
      { nom: "Téléportation",       type: "magie" },
      { nom: "Rapide",              type: "don" },
    ],
    items: [
      { id: 121,  nom: "Bonnet émeraude",   emplacement: "Tête" },    
      { id: 21, nom: "Pèlerine en soie",    emplacement: "Buste" },    
      { id: 54, nom: "Bâton de voyage",     emplacement: "Une main" },    
      { id: 149, nom: "Bottines sylvaines", emplacement: "Pieds" },    
    ],
    drops: [
      { id: 0,   nom: "?" },
    ],
  },
  {
    id: 11,
    name: "Bandit",
    zone: "Zone aléatoire (Kigard)",
    rang: 2,
    hp: 120,
    esq: "?",
    dm: "?",
    arm: 1,
    res: "?",
    competences: [
      { nom: "Disparition soudaine", type: "tech_combat" },
      { nom: "Recherche intuitive",  type: "tech_combat" },
    ],
    items: [
      { id: 162, nom: "Cagoule de l'ombre",  emplacement: "Tête" },    
      { id: 307, nom: "Tunique de l'ombre",  emplacement: "Buste" },    
      { id: 17,  nom: "Arc lourd composite", emplacement: "Deux mains" },    
      { id: 156, nom: "Bottines",            emplacement: "Pieds" },    
    ],
    drops: [
      { id: 365, nom: "Fumigène" },
      { id: 0,   nom: "10-30" },
    ],
  },
  {
    id: 12,
    name: "Chef Bandit",
    zone: "Zone aléatoire (Kigard)",
    rang: 2,
    hp: 120,
    esq: 0,
    dm: 25,
    arm: 13,
    res: 0,
    competences: [
      { nom: "Disloquer",         type: "tech_combat" },
      { nom: "Attaque défensive", type: "tech_combat" },
    ],
    items: [  
      { id: 81, nom: "Cuirasse",           emplacement: "Buste" },    
      { id: 49, nom: "Masse",              emplacement: "Une main" },    
      { id: 29, nom: "Bouclier à pointes", emplacement: "Une main" },    
      { id: 30, nom: "Jambières",          emplacement: "Pieds" },    
    ],
    variantes: [
      [
      { id: 103, nom: "Hache de guerre",    emplacement: "Une main" },    
      { id: 29,  nom: "Bouclier à pointes", emplacement: "Une main" },  
      ],
    ],
    drops: [
      { id: 3,  nom: "Potion de vie mineure" },
      { id: 15, nom: "Potion d'expérience" },
      { id: 298, nom: "Clé en ossements" },
      { id: 0,  nom: "10-30" },
    ],
  },
  {
    id: 28,
    name: "Bandit Barbare",
    zone: "Zone aléatoire (Kigard)",
    rang: 2,
    hp: 120,
    esq: "?",
    dm: "?",
    arm: "?",
    res: "?",
    competences: [
      { nom: "Attaque puissante", type: "tech_combat" },
      { nom: "Enchaîner",         type: "tech_combat" },
    ],
    items: [
      { id: 146, nom: "Bandana en soie",   emplacement: "Tête" },    
      { id: 106, nom: "Ceinture de force", emplacement: "Buste" },    
      { id: 448, nom: "Espadon",           emplacement: "Deux mains" },    
      { id: 156, nom: "Bottines",          emplacement: "Pieds" },     
    ],
    drops: [
      { id: 178, nom: "Potion de vigueur" },
      { id: 0,   nom: "10-30" },
    ],
  },
  {
    id: 7,
    name: "Ogre",
    zone: "Zone aléatoire (Kigard)",
    rang: 2,
    hp: 120,
    esq: 10,
    dm: "?",
    arm: 16,
    res: 0,
    competences: [
      { nom: "Assommer",         type: "tech_combat" },
      { nom: "Coup de bouclier", type: "tech_combat" },
      { nom: "Sauvagerie",       type: "don" },
    ],
    items: [  
      { id: 9,   nom: "Cotte de mailles",    emplacement: "Buste" },    
      { id: 60,  nom: "Fléau d'armes",       emplacement: "Une main" },    
      { id: 28,  nom: "Ecu en cuivre",       emplacement: "Une main" },    
      { id: 260, nom: "Jambières en cuivre", emplacement: "Pieds" },    
    ],
    drops: [
      { id: 15, nom: "Potion d'expérience" },
      { id: 45, nom: "Viande" },
      { id: 0,  nom: "5-30" },
    ],
  },
  {
    id: 13,
    name: "Troll",
    zone: "Zone aléatoire (Kigard)",
    rang: 2,
    hp: 140,
    esq: "?",
    dm: "?",
    arm: "?",
    res: 4,
    competences: [
      { nom: "Attaque puissante",           type: "tech_combat" },
      { nom: "Exécuter",                    type: "tech_combat" },
      { nom: "Régénération",                type: "don" },
      { nom: "Vulnérabilité feu_icone 20%", type: "don" },
    ],
    items: [  
      { id: 155, nom: "Cabasset à cornes", emplacement: "Tête" },    
      { id: 106, nom: "Ceinture de force", emplacement: "Buste" },    
      { id: 108, nom: "Masse géante",      emplacement: "Deux mains" },    
      { id: 64,  nom: "Brodequins",        emplacement: "Pieds" },     
    ],
    drops: [
      { id: 303, nom: "Potion de régénération" },
      { id: 45,  nom: "Viande" },
      { id: 0,   nom: "5-30" },
    ],
  },
  {
    id: 15,
    name: "Troll guérisseur",
    zone: "Zone aléatoire (Kigard)",
    rang: 2,
    hp: 140,
    esq: 0,
    dm: "?",
    arm: 5,
    res: 5,
    competences: [
      { nom: "Piqûre",                      type: "magie" },
      { nom: "Maléfice de poison",          type: "magie" },
      { nom: "Régénération",                type: "don" },
      { nom: "Vulnérabilité feu_icone 20%", type: "don" },
    ],
    items: [
      { id: 319, nom: "Crâne rituel",     emplacement: "Tête" },    
      { id: 74,  nom: "Brigandine",       emplacement: "Buste" },    
      { id: 454, nom: "Bâton de sorcier", emplacement: "Deux mains" },    
      { id: 64,  nom: "Brodequins",       emplacement: "Pieds" },     
    ],
    drops: [
      { id: 61, nom: "Potion d'éther mineure" },
      { id: 0,  nom: "5-30" },
    ],
  },
  {
    id: 3,
    name: "Goblours",
    zone: "Marais & Forêt (Kigard)",
    rang: 1,
    hp: 100,
    esq: 0,
    dm: "?",
    arm: 6,
    res: 2,
    competences: [
      { nom: "Attaque défensive", type: "tech_combat" },
      { nom: "Endurance",         type: "don" },
    ],
    items: [
      { id: 48,  nom: "Armure en cuir", emplacement: "Buste" },    
      { id: 292, nom: "Hachoir",        emplacement: "Une main" },    
      { id: 2,   nom: "Rondache",       emplacement: "Une main" },    
    ],
    variantes: [
      [
      { id: 284, nom: "Gourdin clouté", emplacement: "Une main" },    
      { id: 2,   nom: "Rondache",       emplacement: "Une main" }, 
      ],
    ],
    drops: [
      { id: 0,   nom: "?" },
    ],
  },
  {
    id: 4,
    name: "Vagabond Gobelin",
    zone: "Marais & Forêt (Kigard)",
    rang: 1,
    hp: 80,
    esq: "?",
    dm: 0,
    arm: 3,
    res: 3,
    competences: [
      { nom: "Attaque rapide", type: "tech_combat" },
      { nom: "Sournoiserie",   type: "don" },
    ],
    items: [  
      { id: 48, nom: "Armure en cuir", emplacement: "Buste" },    
      { id: 39, nom: "Arc court",      emplacement: "Une main" },    
      { id: 8,  nom: "Bottes",         emplacement: "Pieds" },   
    ],
    variantes: [
      [
      { id: 1, nom: "Epée courte", emplacement: "Une main" },    
      ],
    ],
    drops: [
      { id: 3, nom: "Potion de vie mineure" },
      { id: 0, nom: "10-20" },
    ],
  },
  {
    id: 5,
    name: "Acolyte Gobelin",
    zone: "Marais & Forêt (Kigard)",
    rang: 1,
    hp: 80,
    esq: "?",
    dm: "?",
    arm: "?",
    res: "?",
    competences: [
      { nom: "Piqûre",       type: "magie" },
      { nom: "Sournoiserie", type: "don" },
    ],
    items: [  
      { id: 166, nom: "Capuchon", emplacement: "Tête" },    
      { id: 18,  nom: "Toge",     emplacement: "Buste" },    
      { id: 23,  nom: "Sceptre",  emplacement: "Une main" },    
    ],
    drops: [
      { id: 0, nom: "?" },
    ],
  },
  {
    id: 128,
    name: "Esclave Gobelin",
    zone: "Marais & Forêt (Kigard)",
    rang: 0,
    hp: 40,
    esq: 0,
    dm: 0,
    arm: 1,
    res: 1,
    competences: [
    ],
    items: [
      { id: 55, nom: "Haillon",       emplacement: "Buste" },    
      { id: 34, nom: "Coutelas", emplacement: "Une main" },    
    ],
    drops: [
      { id: 0, nom: "?" },
    ],
  },
  
  {
    id: 129,
    name: "Shaman Gobelin",
    zone: "Forêt (Kigard)",
    rang: 1,
    hp: 80,
    esq: "?",
    dm: "?",
    arm: 0,
    res: "?",
    competences: [
      { nom: "Boule de feu", type: "magie" }, 
      { nom: "Sournoiserie", type: "don" }, 
    ],
    items: [
      { id: 166, nom: "Capuchon",         emplacement: "Tête" },    
      { id: 18, nom: "Toge",              emplacement: "Buste" },    
      { id: 412, nom: "Bâton d'apprenti", emplacement: "Deux mains" },    
    ],
    drops: [
      { id: 0, nom: "?" },
    ],
  },
  {
    id: 130,
    name: "Incendiaire Gobelin",
    zone: "Forêt (Kigard)",
    rang: 1,
    hp: "?",
    esq: "?",
    dm: 0,
    arm: "?",
    res: 2,
    competences: [
      { nom: "Attaque explosive",        type: "tech_combat" }, 
      { nom: "Sournoiserie",             type: "don" }, 
      { nom: "Résistance feu_icone 30%", type: "don" }, 
    ],
    items: [
      { id: 19,  nom: "Toque",  emplacement: "Tête" },    
      { id: 435, nom: "Torche", emplacement: "Une main" },    
      { id: 8,   nom: "Bottes", emplacement: "Pieds" },     
    ],
    drops: [
      { id: 0, nom: "?" },
    ],
  },
  {
    id: 131,
    name: "Enragé Gobelin",
    zone: "Forêt (Kigard)",
    rang: 1,
    hp: 80,
    esq: "?",
    dm: "?",
    arm: "?",
    res: "?",
    competences: [
      { nom: "Ambidextrie",  type: "tech_combat" }, 
      { nom: "Sournoiserie", type: "don" }, 
    ],
    items: [
      { id: 59,  nom: "Bandana",     emplacement: "Tête" },    
      { id: 292, nom: "Hachoir",     emplacement: "Une main" },    
      { id: 1,   nom: "Epée courte", emplacement: "Une main" },    
    ],
    drops: [
      { id: 0, nom: "10-20" },
    ],
  },
  {
    id: 133,
    name: "Momie",
    zone: "Monstre de quête (Kigard & Nandor)",
    rang: 2,
    hp: 120,
    esq: "?",
    dm: "?",
    arm: "?",
    res: 5,
    competences: [
      { nom: "Attaque défensive",               type: "tech_combat" }, 
      { nom: "Inflige 2 nécrose_icone",         type: "don" }, 
      { nom: "Vulnérabilité feu_icone 30%",     type: "don" }, 
      { nom: "Vulnérabilité lumière_icone 30%", type: "don" }, 
    ],
    items: [
      { id: 74,  nom: "Brigandine",          emplacement: "Buste" },    
      { id: 119, nom: "Falchion",            emplacement: "Une main" },    
      { id: 28,  nom: "Ecu en cuivre",       emplacement: "Une main" },    
      { id: 260, nom: "Jambières en cuivre", emplacement: "Pieds" },    
    ],
    drops: [
      { id: 438, nom: "Elixir d'énergie" },
      { id: 0,   nom: "15-30" },
    ],
  },
  {
    id: 56,
    name: "Démon des orages",
    zone: "Monstre de quête (Kigard & Nandor)",
    rang: 2,
    hp: 110,
    esq: 20,
    dm: 20,
    arm: 0,
    res: 13,
    competences: [
      { nom: "Foudre",                      type: "magie" }, 
      { nom: "Piqûre",                      type: "magie" }, 
      { nom: "Résistance foudre_icone 20%", type: "don" }, 
    ],
    items: [
      { id: 271, nom: "Capuchon en soie",  emplacement: "Tête" },    
      { id: 92,  nom: "Toge en soie",      emplacement: "Buste" },    
      { id: 110, nom: "Crosse tellurique", emplacement: "Une main" },    
      { id: 77,  nom: "Souliers en soie",  emplacement: "Pieds" },    
    ],
    drops: [
      { id: 365, nom: "Fumigène" },
      { id: 0,   nom: "15-30" },
    ],
  },
  {
    id: 34,
    name: "Centaure",
    zone: "Monstre de quête (Kigard & Nandor)",
    rang: 2,
    hp: 150,
    esq: "?",
    dm: "?",
    arm: "?",
    res: "?",
    competences: [
    ],
    items: [
      { id: 168, nom: "Trident",              emplacement: "Une main" },    
      { id: 28,  nom: "Ecu en cuivre",        emplacement: "Une main" },    
      { id: 228, nom: "Talisman du centaure", emplacement: "Fétiche" },    
    ],
    drops: [
      { id: 0, nom: "15-30" },
    ],
  },
  {
    id: 20,
    name: "Abomination",
    zone: "Monstre de quête (Kigard & Nandor)",
    rang: 2,
    hp: 120,
    esq: 20,
    dm: "?",
    arm: 3,
    res: "?",
    competences: [
      { nom: "Tourmenter",                      type: "tech_combat" }, 
      { nom: "Siphonner",                       type: "tech_combat" }, 
      { nom: "Recherche intuitive",             type: "tech_combat" }, 
      { nom: "Inflige 2 terreur_icone",         type: "don" }, 
      { nom: "Vulnérabilité lumière_icone 30%", type: "don" }, 
    ],
    items: [
      { id: 155, nom: "Cabasset à cornes", emplacement: "Tête" },    
      { id: 27,  nom: "Barong",            emplacement: "Une main" },    
      { id: 104, nom: "Lanterne",          emplacement: "Une main" },    
    ],
    drops: [
      { id: 0, nom: "15-30" },
    ],
  },
];